### Register a user

POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "handle": "jimmyjohns",
    "email": "jimmyjohns@sputter.io",
    "password": "password",
    "password2": "password"
}

### Login a user

POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "email": "mattypatty@sputter.io",
    "password": "password"
}

### Post a tweet

POST http://localhost:5000/api/tweets/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYTFlM2E4MTk2MGRhNjkyZjhjYzQ1NyIsImhhbmRsZSI6Im1hdHR5cGF0dHkiLCJlbWFpbCI6Im1hdHR5cGF0dHlAc3B1dHRlci5pbyIsImlhdCI6MTYyMTIyNDI0MywiZXhwIjoxNjIxMjI3ODQzfQ.f05mlALEvT_whQ6AW9cKHcrimk8oh7YggtJTbBJe8AI

{
    "text": "This is the third tweet"
}

### Get a user's tweets
GET http://localhost:5000/api/tweets/user/60a1e3cf1960da692f8cc459
Content-Type: application/json

### Get a specific tweet by id
GET http://localhost:5000/api/tweets/60a1eb001f5d867125b8c9f2
Content-Type: application/json