### Register a user

POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "handle": "jimmyjohns",
    "email": "jimmyjohns@sputter.io",
    "password": "password",
    "password2": "password"
}

### Login a user

POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "email": "mattypatty@sputter.io",
    "password": "password"
}