### Register a user

POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "name": "John Doe",
    "email": "jdoe@anonymous.com",
    "password": "password",
    "password2": "password"
}

### Login a user

POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "email": "tomhanks@savingprivateryan.com",
    "password": "password"
}

### Post a post

POST http://localhost:5000/api/posts/
Content-Type: application/json
Authorization: Bearer <token>

{
    "title": "Hi, I'm Tom Hanks",
    "body": "We succeeded.",
    "author": "60b12b4644578762dbea244c"
}

### Get a user's tweets
GET http://localhost:5000/api/tweets/user/60a1e3cf1960da692f8cc459
Content-Type: application/json

### Get a specific tweet by id
GET http://localhost:5000/api/tweets/60a1eb001f5d867125b8c9f2
Content-Type: application/json